image: jakzal/phpqa:php7.4

before_script:
  - composer install -d project/

cache:
  paths:
    - project/vendor/
    - project/node_modules

stages:
  - SecurityChecker

security-checker:
  stage: SecurityChecker
  script:
    - local-php-security-checker  --path=./project/composer.lock
  allow_failure: false